---
- hosts: all
  become: true
  vars:
    mysql_root_password: strong_password
  tasks:
    - name: Updating apt cache 
      apt: 
        upgrade: no
        update_cache: yes

    - name: Install MySQL
      apt: name={{ item }} update_cache=no state=present
      with_items:
        - python-mysqldb
        - mysql-server

    - name: Start the MySQL service
      service: 
        name: mysql 
        state: started
        enabled: true

    - name: update mysql root password for all root accounts
      mysql_user: 
        name: root 
        host: "{{ item }}" 
        password: "{{ mysql_root_password }}"
        login_user: root
        login_password: "{{ mysql_root_password }}"
        check_implicit_admin: yes
        priv: "*.*:ALL,GRANT"
      with_items:
        - "{{ ansible_hostname }}"
        - "{{ ansible_default_ipv4.address }}"
        - 127.0.0.1
        - ::1
        - localhost 
