---
- hosts: all
  become: true
  vars:
    mysql_root_password: strong_password
  tasks:
    - name: Updating apt cache 
      apt: 
        upgrade: no
        update_cache: yes
        cache_valid_time: 36000

    - name: Install necessary packages
      apt: name={{ item }} update_cache=no state=present
      with_items:
        - python-mysqldb
        - mysql-server
        - python-dev 
        - libmysqlclient-dev
        - python-pip

    - name: Start the MySQL service
      service: 
        name: mysql 
        state: started
        enabled: true

    - name: update mysql root password for all root accounts
      mysql_user: 
        name: root 
        host: "{{ item }}" 
        password: "{{ mysql_root_password }}"
        login_user: root
        login_password: "{{ mysql_root_password }}"
        check_implicit_admin: yes
        priv: "*.*:ALL,GRANT"
      with_items:
        - "{{ ansible_hostname }}"
        - "{{ ansible_default_ipv4.address }}"
        - 127.0.0.1
        - ::1
        - localhost 
    - name: Installing python MySQL connector
      pip: 
        name: "{{ item }}"
      with_items:
        - MySQL-python
        - mysql-connector
    - name: Copying python file to server
      copy: 
        src: ../Server.py 
        dest: /usr/local/bin/Server.py
    - name: Making file executable
      file: 
        path: /usr/local/bin/Server.py
        owner: root
        group: root
        mode: 0755